name: Update Release Branch
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  update-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update release branch
        run: |
          git checkout release
          git reset --hard ${{ github.ref_name }}
          git push origin release
